from PIL import Image
import streamlit as st
img_contact_form = Image.open("images/Cross.png")
img_contact_form = Image.open("images/cross_1.png")
img_contact_form = Image.open("images/cross_2.png")
img_contact_form= Image.open("images/F2L.png")
img_contact_form = Image.open("images/Hedge.png")
img_contact_form= Image.open("images/sledge.png")
st.set_page_config(page_title="Why CFOP is best", page_icon="images/icon.png")
st.title("Why CFOP is the best method")
st.write("---")
st.write("1. CFOP is easy to learn and can be learned with a [tutorial](https://youtu.be/Tvt85mW28vo?si=DJ1KHgfuU26usRUS) or from a [website](https://jperm.net/3x3/cfop)")
st.write("2. CFOP really easy to understand")
st.write("3. CFOP mostly algorithm based so muscle memory is used more then your mind")
st.write("4. CFOP used by Yiheng Wang")
st.write("5. CFOP is fast in its steps")
st.write("[learn more>](https://www.speedsolving.com/threads/why-is-cfop-the-best-method.62833/) from the community")
st.write("---")
st.title("Learn CFOP (Cross and F2L only)")
st.write("---")
st.write("---")
image_column,text_column = st.columns((1,2))
with image_column:
    st.title("Cross (any side)")
    st.image("images/Cross.png")
st.write("---")
st.write("There are multiple cases of the cross but since were a beginner, its just gonna be easy")
image_column, text_column = st.columns((1,2))
with image_column:
        st.image("images/cross_1.png")
st.write("U' R' F R")
st.write("---")
image_column, text_column = st.columns((1,2))
with image_column:
    st.image("images/cross_2.png")
    st.write("F2")
st.write("---")
image_column, text_column = st.columns ((1,2))
with image_column:
    st.image("images/F2L.png")
st.title("f2l (first two layers)")
st.write("---")
st.write("F2l is a harder step then the cross so I will just show 2 cases when the pair is solved")
image_column, text_column = st.columns((1,2))
with image_column:
    st.image("images/Hedge.png")
st.write("F R' F' R")
st.write("---")
image_column, text_column =st.columns((1,2))
with image_column:
    st.image("images/sledge.png")
st.write("R' F R F'")
st.write("---")
st.title("extra message")
st.write("---")
st.write("I hope this website helped you :D")
st.write("I know its short but im just gonna put some links to a tutorial on youtube")
st.write("[F2L](https://youtu.be/ReOZZHscIGk?si=LqUIUaghSkZVnOo6)")
st.write("[OLL](https://youtu.be/6PSBaxlBqRg?si=Rwumg3-rxMHk1oHM)")
st.write("[PLL](https://youtu.be/ZC9nwou59ow?si=XxOmhMy6e613b3jH)")